name: Java CI

on:
  push:
    branches: [main , dev ]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code татах
        uses: actions/checkout@v4

      - name: Java 17 суулгах
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Тест ажиллуулах
        run: mvn test